### PR TITLE
 Update SPGA2_forSingleMachine.java , Create objectiveTC.java , objectiveTADC.java

### PR DESCRIPTION
**Pull request by picashuo**
Update  SPGA2_forSingleMachine.java 129-132

### CODE REVIEW

**Comment by worldstar** [comment]
We may put the class name after the comment. Or we create a new class instead.
ObjectiveFunction[0] = new ObjectiveEarlinessForSingleMachine();//the first objective
ObjectiveFunction[1] = new ObjectiveTardinessForSingleMachine();//the second one.

**Comment by worldstar** [comment]
A simple revision to test the SPGAII on a two-objective single machine scheduling problems.

**Comment by worldstar** [comment]
The same commit.

**Comment by picashuo** [comment]
好的 謝謝老師

**Pull request merged**
